### ISSUE TITLE
Remove height and width limitation from body element

### ISSUE THREAD

**Issue by vuxor** [Mina-S93/Prvi-zadatak#1]
https://github.com/Mina-S93/Prvi-zadatak/blob/bd67096d55c0507e0c772740c6cf2e6960e470f2/style.css#L10-L11
There is no need for this limitation on body element.
Please remove it and fix the card height issue on mobile and also on desktop when browser height is changing.

**Comment by Mina-S93** [comment]
> https://github.com/Mina-S93/Prvi-zadatak/blob/bd67096d55c0507e0c772740c6cf2e6960e470f2/style.css#L10-L11
> 
> 
> There is no need for this limitation on body element.
> Please remove it and fix the card height issue on mobile and also on desktop when browser height is changing.

I fixed the issue by changing the units to rem and I also deleted unnecessary body limitations.
